const data = new Date()

const ano = data.getFullYear()
const mes = data.getMonth()
const dia = data.getDate()
const horas = data.getHours()
const minutos = data.getMinutes()
console.log(`${dia}/0${mes + 1}/${ano}`)
console.log(`${horas}:${minutos}`)
console.log(data)
